services:
  postgres:
    image: postgres:17.4
    restart: always
    env_file:
      - todolist/.env
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready - U postgres
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
volumes:
  pg_data_todolist:
networks:
  backend_nw:
    driver: bridge